### ISSUE TITLE
[FYI] Available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [jovandeginste/payme#5]
This “issue” is purely informational, and may be closed at your discretion. No action, now or later, is necessary on your part.

Payme is available from AUR as [payme.git](https://aur.archlinux.org/packages/payme-git):

* https://aur.archlinux.org/packages/payme-git

The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=payme-git) will build the binary from the latest commit and install it along with the shell completions and the license.

Cheers.

**Comment by jovandeginste** [comment]
Thank you! ❤️
